CREATE TABLE users IF NOT EXISTS(
    user_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_name VARCHAR(256) NOT NULL,
    email_address VARCHAR(256) NOT NULL,
    user_password VARCHAR(1024) NOT NULL
);